name: meu_app
description: "Aplicativo para controle de regador automático de plantas"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  cloud_firestore: ^5.0.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.69.0



  # UI/UX
  cupertino_icons: ^1.0.6
  
  # State Management (opcional, para futuras expansões)
  # provider: ^6.1.1
  # flutter_bloc: ^8.1.3
  
  # Local Storage (para salvar dados das plantas)
  # shared_preferences: ^2.2.2
  # sqflite: ^2.3.0
  
  # Network (para comunicação com sensores IoT)
  # http: ^1.1.0
  # dio: ^5.3.2
  
  # Charts (para gráficos de dados)
  # fl_chart: ^0.64.0
  # syncfusion_flutter_charts: ^23.1.44
  
  # Notifications
  # flutter_local_notifications: ^16.1.0
  
  # Device Info
  # device_info_plus: ^9.1.0
  
  # Permissions
  # permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/images/plantas/
    - assets/images/automacao/
  
  # Fonts (opcional, para fontes customizadas)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700